name: Sonar Build
on:
   workflow_dispatch:
   push:
    branches: [ dev ]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectName=anudan-app/dev
            -Dsonar.organization=anudan1
            -Dsonar.projectKey=anudan-app
            -Dsonar.projectVersion=1.0
            -Dsonar.sources=src/app
            -Dsonar.exclusions=src/app/**.spec.ts
            -Dsonar.sourceEncoding=UTF-8
